# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-collection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tmy_variable_pb2 as tmy__variable__pb2
from . import event_pb2 as event__pb2
from . import data_frame_pb2 as data__frame__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='data-collection.proto',
  package='data.collection',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x64\x61ta-collection.proto\x12\x0f\x64\x61ta.collection\x1a\x12tmy-variable.proto\x1a\x0b\x65vent.proto\x1a\x10\x64\x61ta-frame.proto\"\xc1\x01\n\x14\x44\x61taCollectionRecord\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).data.collection.DataCollectionRecordType\x12(\n\x08variable\x18\x02 \x01(\x0b\x32\x16.tmy.variable.Variable\x12\x1b\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x0c.event.Event\x12)\n\ndata_frame\x18\x04 \x01(\x0b\x32\x15.data.frame.DataFrame\"L\n\x0e\x44\x61taCollection\x12:\n\x0brecord_list\x18\x01 \x03(\x0b\x32%.data.collection.DataCollectionRecord*C\n\x18\x44\x61taCollectionRecordType\x12\x0c\n\x08VARIABLE\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x12\x0e\n\nDATA_FRAME\x10\x02\x42U\n<com.invap.mulitas.serialization.impl.protobuf.datacollectionB\x15\x44\x61taCollectionPackage')
  ,
  dependencies=[tmy__variable__pb2.DESCRIPTOR,event__pb2.DESCRIPTOR,data__frame__pb2.DESCRIPTOR,])

_DATACOLLECTIONRECORDTYPE = _descriptor.EnumDescriptor(
  name='DataCollectionRecordType',
  full_name='data.collection.DataCollectionRecordType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VARIABLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_FRAME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=367,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_DATACOLLECTIONRECORDTYPE)

DataCollectionRecordType = enum_type_wrapper.EnumTypeWrapper(_DATACOLLECTIONRECORDTYPE)
VARIABLE = 0
EVENT = 1
DATA_FRAME = 2



_DATACOLLECTIONRECORD = _descriptor.Descriptor(
  name='DataCollectionRecord',
  full_name='data.collection.DataCollectionRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='data.collection.DataCollectionRecord.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variable', full_name='data.collection.DataCollectionRecord.variable', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='data.collection.DataCollectionRecord.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_frame', full_name='data.collection.DataCollectionRecord.data_frame', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=287,
)


_DATACOLLECTION = _descriptor.Descriptor(
  name='DataCollection',
  full_name='data.collection.DataCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_list', full_name='data.collection.DataCollection.record_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=365,
)

_DATACOLLECTIONRECORD.fields_by_name['type'].enum_type = _DATACOLLECTIONRECORDTYPE
_DATACOLLECTIONRECORD.fields_by_name['variable'].message_type = tmy__variable__pb2._VARIABLE
_DATACOLLECTIONRECORD.fields_by_name['event'].message_type = event__pb2._EVENT
_DATACOLLECTIONRECORD.fields_by_name['data_frame'].message_type = data__frame__pb2._DATAFRAME
_DATACOLLECTION.fields_by_name['record_list'].message_type = _DATACOLLECTIONRECORD
DESCRIPTOR.message_types_by_name['DataCollectionRecord'] = _DATACOLLECTIONRECORD
DESCRIPTOR.message_types_by_name['DataCollection'] = _DATACOLLECTION
DESCRIPTOR.enum_types_by_name['DataCollectionRecordType'] = _DATACOLLECTIONRECORDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataCollectionRecord = _reflection.GeneratedProtocolMessageType('DataCollectionRecord', (_message.Message,), dict(
  DESCRIPTOR = _DATACOLLECTIONRECORD,
  __module__ = 'data_collection_pb2'
  # @@protoc_insertion_point(class_scope:data.collection.DataCollectionRecord)
  ))
_sym_db.RegisterMessage(DataCollectionRecord)

DataCollection = _reflection.GeneratedProtocolMessageType('DataCollection', (_message.Message,), dict(
  DESCRIPTOR = _DATACOLLECTION,
  __module__ = 'data_collection_pb2'
  # @@protoc_insertion_point(class_scope:data.collection.DataCollection)
  ))
_sym_db.RegisterMessage(DataCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n<com.invap.mulitas.serialization.impl.protobuf.datacollectionB\025DataCollectionPackage'))
# @@protoc_insertion_point(module_scope)
