# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datatypes_pb2 as datatypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='data-frame.proto',
  package='data.frame',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x64\x61ta-frame.proto\x12\ndata.frame\x1a\x0f\x64\x61tatypes.proto\"c\n\tDataFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x1f\n\x17\x64\x61taFrameTypeIdentifier\x18\x02 \x01(\t\x12\'\n\ttimestamp\x18\x03 \x01(\x0b\x32\x14.datatypes.TimeStampBK\n7com.invap.mulitas.serialization.impl.protobuf.dataframeB\x10\x44\x61taFramePackage')
  ,
  dependencies=[datatypes__pb2.DESCRIPTOR,])




_DATAFRAME = _descriptor.Descriptor(
  name='DataFrame',
  full_name='data.frame.DataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='data.frame.DataFrame.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataFrameTypeIdentifier', full_name='data.frame.DataFrame.dataFrameTypeIdentifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.frame.DataFrame.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=148,
)

_DATAFRAME.fields_by_name['timestamp'].message_type = datatypes__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['DataFrame'] = _DATAFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataFrame = _reflection.GeneratedProtocolMessageType('DataFrame', (_message.Message,), dict(
  DESCRIPTOR = _DATAFRAME,
  __module__ = 'data_frame_pb2'
  # @@protoc_insertion_point(class_scope:data.frame.DataFrame)
  ))
_sym_db.RegisterMessage(DataFrame)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n7com.invap.mulitas.serialization.impl.protobuf.dataframeB\020DataFramePackage'))
# @@protoc_insertion_point(module_scope)
