# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatypes.proto',
  package='datatypes',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64\x61tatypes.proto\x12\tdatatypes\"\x18\n\x07\x42oolean\x12\r\n\x05value\x18\x01 \x01(\x08\"\x88\x01\n\nFixedPoint\x12(\n\x04sign\x18\x01 \x01(\x0e\x32\x1a.datatypes.FixedPoint.Sign\x12\x13\n\x0bscaleFactor\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\x04\",\n\x04Sign\x12\x11\n\rSign_POSITIVE\x10\x00\x12\x11\n\rSign_NEGATIVE\x10\x01\"\x1e\n\rFloatingPoint\x12\r\n\x05value\x18\x01 \x01(\x01\"\x18\n\x07Integer\x12\r\n\x05value\x18\x01 \x01(\x03\"X\n\x0bLongInteger\x12#\n\x07lowPart\x18\x01 \x01(\x0b\x32\x12.datatypes.Integer\x12$\n\x08highPart\x18\x02 \x01(\x0b\x32\x12.datatypes.Integer\"1\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\x13\n\x0bnanoseconds\x18\x02 \x01(\x03\"\x18\n\x07Literal\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nByteStream\x12\r\n\x05value\x18\x01 \x01(\x0c\"\xe9\x01\n\x06Number\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.datatypes.NumberType\x12\x33\n\x11\x66loatinPointValue\x18\x02 \x01(\x0b\x32\x18.datatypes.FloatingPoint\x12.\n\x0f\x66ixedPointValue\x18\x03 \x01(\x0b\x32\x15.datatypes.FixedPoint\x12(\n\x0cintegerValue\x18\x04 \x01(\x0b\x32\x12.datatypes.Integer\x12+\n\x0blongInteger\x18\x05 \x01(\x0b\x32\x16.datatypes.LongInteger\"\x95\x01\n\x07\x41nyType\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.datatypes.AnyTypeType\x12&\n\x0bnumberValue\x18\x02 \x01(\x0b\x32\x11.datatypes.Number\x12\x13\n\x0bstringValue\x18\x03 \x01(\t\x12\x14\n\x0c\x62ooleanValue\x18\x04 \x01(\x08\x12\x11\n\tbyteValue\x18\x05 \x01(\x0c*M\n\nNumberType\x12\x0f\n\x0b\x46LOAT_POINT\x10\x00\x12\x0f\n\x0b\x46IXED_POINT\x10\x01\x12\x0b\n\x07INTEGER\x10\x02\x12\x10\n\x0cLONG_INTEGER\x10\x03*=\n\x0b\x41nyTypeType\x12\n\n\x06NUMBER\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05\x42YTES\x10\x02\x12\x0b\n\x07\x42OOLEAN\x10\x03\x42/\n-com.invap.mulitas.serialization.impl.protobuf')
)

_NUMBERTYPE = _descriptor.EnumDescriptor(
  name='NumberType',
  full_name='datatypes.NumberType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT_POINT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXED_POINT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTEGER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LONG_INTEGER', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=837,
  serialized_end=914,
)
_sym_db.RegisterEnumDescriptor(_NUMBERTYPE)

NumberType = enum_type_wrapper.EnumTypeWrapper(_NUMBERTYPE)
_ANYTYPETYPE = _descriptor.EnumDescriptor(
  name='AnyTypeType',
  full_name='datatypes.AnyTypeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NUMBER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOLEAN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=916,
  serialized_end=977,
)
_sym_db.RegisterEnumDescriptor(_ANYTYPETYPE)

AnyTypeType = enum_type_wrapper.EnumTypeWrapper(_ANYTYPETYPE)
FLOAT_POINT = 0
FIXED_POINT = 1
INTEGER = 2
LONG_INTEGER = 3
NUMBER = 0
STRING = 1
BYTES = 2
BOOLEAN = 3


_FIXEDPOINT_SIGN = _descriptor.EnumDescriptor(
  name='Sign',
  full_name='datatypes.FixedPoint.Sign',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Sign_POSITIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sign_NEGATIVE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=149,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_FIXEDPOINT_SIGN)


_BOOLEAN = _descriptor.Descriptor(
  name='Boolean',
  full_name='datatypes.Boolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.Boolean.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_FIXEDPOINT = _descriptor.Descriptor(
  name='FixedPoint',
  full_name='datatypes.FixedPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sign', full_name='datatypes.FixedPoint.sign', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaleFactor', full_name='datatypes.FixedPoint.scaleFactor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.FixedPoint.value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIXEDPOINT_SIGN,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=193,
)


_FLOATINGPOINT = _descriptor.Descriptor(
  name='FloatingPoint',
  full_name='datatypes.FloatingPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.FloatingPoint.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=225,
)


_INTEGER = _descriptor.Descriptor(
  name='Integer',
  full_name='datatypes.Integer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.Integer.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=251,
)


_LONGINTEGER = _descriptor.Descriptor(
  name='LongInteger',
  full_name='datatypes.LongInteger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lowPart', full_name='datatypes.LongInteger.lowPart', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='highPart', full_name='datatypes.LongInteger.highPart', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=341,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='datatypes.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='datatypes.TimeStamp.seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanoseconds', full_name='datatypes.TimeStamp.nanoseconds', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=392,
)


_LITERAL = _descriptor.Descriptor(
  name='Literal',
  full_name='datatypes.Literal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.Literal.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=418,
)


_BYTESTREAM = _descriptor.Descriptor(
  name='ByteStream',
  full_name='datatypes.ByteStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datatypes.ByteStream.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=447,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='datatypes.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='datatypes.Number.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floatinPointValue', full_name='datatypes.Number.floatinPointValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fixedPointValue', full_name='datatypes.Number.fixedPointValue', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integerValue', full_name='datatypes.Number.integerValue', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longInteger', full_name='datatypes.Number.longInteger', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=683,
)


_ANYTYPE = _descriptor.Descriptor(
  name='AnyType',
  full_name='datatypes.AnyType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='datatypes.AnyType.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberValue', full_name='datatypes.AnyType.numberValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringValue', full_name='datatypes.AnyType.stringValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='booleanValue', full_name='datatypes.AnyType.booleanValue', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='byteValue', full_name='datatypes.AnyType.byteValue', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=835,
)

_FIXEDPOINT.fields_by_name['sign'].enum_type = _FIXEDPOINT_SIGN
_FIXEDPOINT_SIGN.containing_type = _FIXEDPOINT
_LONGINTEGER.fields_by_name['lowPart'].message_type = _INTEGER
_LONGINTEGER.fields_by_name['highPart'].message_type = _INTEGER
_NUMBER.fields_by_name['type'].enum_type = _NUMBERTYPE
_NUMBER.fields_by_name['floatinPointValue'].message_type = _FLOATINGPOINT
_NUMBER.fields_by_name['fixedPointValue'].message_type = _FIXEDPOINT
_NUMBER.fields_by_name['integerValue'].message_type = _INTEGER
_NUMBER.fields_by_name['longInteger'].message_type = _LONGINTEGER
_ANYTYPE.fields_by_name['type'].enum_type = _ANYTYPETYPE
_ANYTYPE.fields_by_name['numberValue'].message_type = _NUMBER
DESCRIPTOR.message_types_by_name['Boolean'] = _BOOLEAN
DESCRIPTOR.message_types_by_name['FixedPoint'] = _FIXEDPOINT
DESCRIPTOR.message_types_by_name['FloatingPoint'] = _FLOATINGPOINT
DESCRIPTOR.message_types_by_name['Integer'] = _INTEGER
DESCRIPTOR.message_types_by_name['LongInteger'] = _LONGINTEGER
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Literal'] = _LITERAL
DESCRIPTOR.message_types_by_name['ByteStream'] = _BYTESTREAM
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['AnyType'] = _ANYTYPE
DESCRIPTOR.enum_types_by_name['NumberType'] = _NUMBERTYPE
DESCRIPTOR.enum_types_by_name['AnyTypeType'] = _ANYTYPETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Boolean = _reflection.GeneratedProtocolMessageType('Boolean', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEAN,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.Boolean)
  ))
_sym_db.RegisterMessage(Boolean)

FixedPoint = _reflection.GeneratedProtocolMessageType('FixedPoint', (_message.Message,), dict(
  DESCRIPTOR = _FIXEDPOINT,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.FixedPoint)
  ))
_sym_db.RegisterMessage(FixedPoint)

FloatingPoint = _reflection.GeneratedProtocolMessageType('FloatingPoint', (_message.Message,), dict(
  DESCRIPTOR = _FLOATINGPOINT,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.FloatingPoint)
  ))
_sym_db.RegisterMessage(FloatingPoint)

Integer = _reflection.GeneratedProtocolMessageType('Integer', (_message.Message,), dict(
  DESCRIPTOR = _INTEGER,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.Integer)
  ))
_sym_db.RegisterMessage(Integer)

LongInteger = _reflection.GeneratedProtocolMessageType('LongInteger', (_message.Message,), dict(
  DESCRIPTOR = _LONGINTEGER,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.LongInteger)
  ))
_sym_db.RegisterMessage(LongInteger)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

Literal = _reflection.GeneratedProtocolMessageType('Literal', (_message.Message,), dict(
  DESCRIPTOR = _LITERAL,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.Literal)
  ))
_sym_db.RegisterMessage(Literal)

ByteStream = _reflection.GeneratedProtocolMessageType('ByteStream', (_message.Message,), dict(
  DESCRIPTOR = _BYTESTREAM,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.ByteStream)
  ))
_sym_db.RegisterMessage(ByteStream)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.Number)
  ))
_sym_db.RegisterMessage(Number)

AnyType = _reflection.GeneratedProtocolMessageType('AnyType', (_message.Message,), dict(
  DESCRIPTOR = _ANYTYPE,
  __module__ = 'datatypes_pb2'
  # @@protoc_insertion_point(class_scope:datatypes.AnyType)
  ))
_sym_db.RegisterMessage(AnyType)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n-com.invap.mulitas.serialization.impl.protobuf'))
# @@protoc_insertion_point(module_scope)
