# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event-alarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event-alarm.proto',
  package='event.alarm',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x65vent-alarm.proto\x12\x0b\x65vent.alarm\x1a\x0emetadata.proto\"\x8f\x01\n\x13\x41larmTriggeredEvent\x12$\n\x08metadata\x18\x01 \x01(\x0b\x32\x12.metadata.Metadata\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\treference\x18\x04 \x01(\t\x12\x19\n\x11\x61larm_instance_id\x18\x05 \x01(\t\"\xae\x01\n\x15\x41larmAcknowlegedEvent\x12$\n\x08metadata\x18\x01 \x01(\x0b\x32\x12.metadata.Metadata\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\treference\x18\x04 \x01(\t\x12\x19\n\x11\x61larm_instance_id\x18\x05 \x01(\t\x12\x1b\n\x13\x61\x63knowleging_entity\x18\x06 \x01(\tB;\n9com.invap.mulitas.serialization.impl.protobuf.event.alarm')
  ,
  dependencies=[metadata__pb2.DESCRIPTOR,])




_ALARMTRIGGEREDEVENT = _descriptor.Descriptor(
  name='AlarmTriggeredEvent',
  full_name='event.alarm.AlarmTriggeredEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='event.alarm.AlarmTriggeredEvent.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='event.alarm.AlarmTriggeredEvent.summary', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='event.alarm.AlarmTriggeredEvent.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reference', full_name='event.alarm.AlarmTriggeredEvent.reference', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_instance_id', full_name='event.alarm.AlarmTriggeredEvent.alarm_instance_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=194,
)


_ALARMACKNOWLEGEDEVENT = _descriptor.Descriptor(
  name='AlarmAcknowlegedEvent',
  full_name='event.alarm.AlarmAcknowlegedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='event.alarm.AlarmAcknowlegedEvent.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='event.alarm.AlarmAcknowlegedEvent.summary', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='event.alarm.AlarmAcknowlegedEvent.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reference', full_name='event.alarm.AlarmAcknowlegedEvent.reference', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_instance_id', full_name='event.alarm.AlarmAcknowlegedEvent.alarm_instance_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acknowleging_entity', full_name='event.alarm.AlarmAcknowlegedEvent.acknowleging_entity', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=371,
)

_ALARMTRIGGEREDEVENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
_ALARMACKNOWLEGEDEVENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
DESCRIPTOR.message_types_by_name['AlarmTriggeredEvent'] = _ALARMTRIGGEREDEVENT
DESCRIPTOR.message_types_by_name['AlarmAcknowlegedEvent'] = _ALARMACKNOWLEGEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlarmTriggeredEvent = _reflection.GeneratedProtocolMessageType('AlarmTriggeredEvent', (_message.Message,), dict(
  DESCRIPTOR = _ALARMTRIGGEREDEVENT,
  __module__ = 'event_alarm_pb2'
  # @@protoc_insertion_point(class_scope:event.alarm.AlarmTriggeredEvent)
  ))
_sym_db.RegisterMessage(AlarmTriggeredEvent)

AlarmAcknowlegedEvent = _reflection.GeneratedProtocolMessageType('AlarmAcknowlegedEvent', (_message.Message,), dict(
  DESCRIPTOR = _ALARMACKNOWLEGEDEVENT,
  __module__ = 'event_alarm_pb2'
  # @@protoc_insertion_point(class_scope:event.alarm.AlarmAcknowlegedEvent)
  ))
_sym_db.RegisterMessage(AlarmAcknowlegedEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n9com.invap.mulitas.serialization.impl.protobuf.event.alarm'))
# @@protoc_insertion_point(module_scope)
