# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import event_generic_pb2 as event__generic__pb2
from . import event_alarm_pb2 as event__alarm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='event',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x05\x65vent\x1a\x13\x65vent-generic.proto\x1a\x11\x65vent-alarm.proto\"\xdc\x01\n\x05\x45vent\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.event.EventType\x12\x31\n\x0cgenericEvent\x18\x02 \x01(\x0b\x32\x1b.event.generic.GenericEvent\x12=\n\x13\x61larmTriggeredEvent\x18\x03 \x01(\x0b\x32 .event.alarm.AlarmTriggeredEvent\x12\x41\n\x15\x61larmAcknowlegedEvent\x18\x04 \x01(\x0b\x32\".event.alarm.AlarmAcknowlegedEvent*\xa3\x01\n\tEventType\x12\x1c\n\x18\x41LARM_INSTANCE_TRIGGERED\x10\x00\x12\x15\n\x11\x41LARM_ACKNOWLEGED\x10\x01\x12\x12\n\x0eINFRASTRCUTURE\x10\x03\x12\x0c\n\x08OPERATOR\x10\x04\x12\x0b\n\x07TESTING\x10\x05\x12\x15\n\x11\x44\x45VICE_UNDER_TEST\x10\x06\x12\x0e\n\nTEST_SETUP\x10\x07\x12\x0b\n\x07GENERIC\x10\x08\x42\x43\n3com.invap.mulitas.serialization.impl.protobuf.eventB\x0c\x45ventPackage')
  ,
  dependencies=[event__generic__pb2.DESCRIPTOR,event__alarm__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='event.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALARM_INSTANCE_TRIGGERED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALARM_ACKNOWLEGED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFRASTRCUTURE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPERATOR', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TESTING', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_UNDER_TEST', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_SETUP', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERIC', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=286,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
ALARM_INSTANCE_TRIGGERED = 0
ALARM_ACKNOWLEGED = 1
INFRASTRCUTURE = 3
OPERATOR = 4
TESTING = 5
DEVICE_UNDER_TEST = 6
TEST_SETUP = 7
GENERIC = 8



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='event.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='event.Event.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genericEvent', full_name='event.Event.genericEvent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmTriggeredEvent', full_name='event.Event.alarmTriggeredEvent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmAcknowlegedEvent', full_name='event.Event.alarmAcknowlegedEvent', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=283,
)

_EVENT.fields_by_name['type'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['genericEvent'].message_type = event__generic__pb2._GENERICEVENT
_EVENT.fields_by_name['alarmTriggeredEvent'].message_type = event__alarm__pb2._ALARMTRIGGEREDEVENT
_EVENT.fields_by_name['alarmAcknowlegedEvent'].message_type = event__alarm__pb2._ALARMACKNOWLEGEDEVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.Event)
  ))
_sym_db.RegisterMessage(Event)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.invap.mulitas.serialization.impl.protobuf.eventB\014EventPackage'))
# @@protoc_insertion_point(module_scope)
