# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event-generic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event-generic.proto',
  package='event.generic',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x65vent-generic.proto\x12\revent.generic\x1a\x0emetadata.proto\"k\n\x0cGenericEvent\x12$\n\x08metadata\x18\x01 \x01(\x0b\x32\x12.metadata.Metadata\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07subtype\x18\x04 \x01(\tB=\n;com.invap.mulitas.serialization.impl.protobuf.event.generic')
  ,
  dependencies=[metadata__pb2.DESCRIPTOR,])




_GENERICEVENT = _descriptor.Descriptor(
  name='GenericEvent',
  full_name='event.generic.GenericEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='event.generic.GenericEvent.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='event.generic.GenericEvent.summary', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='event.generic.GenericEvent.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtype', full_name='event.generic.GenericEvent.subtype', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=161,
)

_GENERICEVENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
DESCRIPTOR.message_types_by_name['GenericEvent'] = _GENERICEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericEvent = _reflection.GeneratedProtocolMessageType('GenericEvent', (_message.Message,), dict(
  DESCRIPTOR = _GENERICEVENT,
  __module__ = 'event_generic_pb2'
  # @@protoc_insertion_point(class_scope:event.generic.GenericEvent)
  ))
_sym_db.RegisterMessage(GenericEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n;com.invap.mulitas.serialization.impl.protobuf.event.generic'))
# @@protoc_insertion_point(module_scope)
