# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement-amount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import measurement_unit_pb2 as measurement__unit__pb2
from . import metadata_pb2 as metadata__pb2
from . import datatypes_pb2 as datatypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurement-amount.proto',
  package='measurement.amount',
  syntax='proto2',
  serialized_pb=_b('\n\x18measurement-amount.proto\x12\x12measurement.amount\x1a\x16measurement-unit.proto\x1a\x0emetadata.proto\x1a\x0f\x64\x61tatypes.proto\"\xd2\x01\n\x11\x41mountMeasurement\x12 \n\x05value\x18\x01 \x01(\x0b\x32\x11.datatypes.Number\x12\r\n\x05valid\x18\x02 \x01(\x08\x12$\n\x04unit\x18\x03 \x01(\x0e\x32\x16.measurement.unit.Unit\x12\x31\n\x0bunit_prefix\x18\x04 \x01(\x0e\x32\x1c.measurement.unit.UnitPrefix\x12\r\n\x05\x65rror\x18\x05 \x01(\x02\x12$\n\x08metadata\x18\x0f \x01(\x0b\x32\x12.metadata.MetadataB;\n9com.invap.mulitas.serialization.impl.protobuf.measurement')
  ,
  dependencies=[measurement__unit__pb2.DESCRIPTOR,metadata__pb2.DESCRIPTOR,datatypes__pb2.DESCRIPTOR,])




_AMOUNTMEASUREMENT = _descriptor.Descriptor(
  name='AmountMeasurement',
  full_name='measurement.amount.AmountMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='measurement.amount.AmountMeasurement.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='measurement.amount.AmountMeasurement.valid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='measurement.amount.AmountMeasurement.unit', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_prefix', full_name='measurement.amount.AmountMeasurement.unit_prefix', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='measurement.amount.AmountMeasurement.error', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='measurement.amount.AmountMeasurement.metadata', index=5,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=316,
)

_AMOUNTMEASUREMENT.fields_by_name['value'].message_type = datatypes__pb2._NUMBER
_AMOUNTMEASUREMENT.fields_by_name['unit'].enum_type = measurement__unit__pb2._UNIT
_AMOUNTMEASUREMENT.fields_by_name['unit_prefix'].enum_type = measurement__unit__pb2._UNITPREFIX
_AMOUNTMEASUREMENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
DESCRIPTOR.message_types_by_name['AmountMeasurement'] = _AMOUNTMEASUREMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AmountMeasurement = _reflection.GeneratedProtocolMessageType('AmountMeasurement', (_message.Message,), dict(
  DESCRIPTOR = _AMOUNTMEASUREMENT,
  __module__ = 'measurement_amount_pb2'
  # @@protoc_insertion_point(class_scope:measurement.amount.AmountMeasurement)
  ))
_sym_db.RegisterMessage(AmountMeasurement)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n9com.invap.mulitas.serialization.impl.protobuf.measurement'))
# @@protoc_insertion_point(module_scope)
