# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement-unavail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurement-unavail.proto',
  package='measurement.unavail',
  syntax='proto2',
  serialized_pb=_b('\n\x19measurement-unavail.proto\x12\x13measurement.unavail\x1a\x0emetadata.proto\">\n\x16UnavailableMeasurement\x12$\n\x08metadata\x18\x0f \x01(\x0b\x32\x12.metadata.MetadataB;\n9com.invap.mulitas.serialization.impl.protobuf.measurement')
  ,
  dependencies=[metadata__pb2.DESCRIPTOR,])




_UNAVAILABLEMEASUREMENT = _descriptor.Descriptor(
  name='UnavailableMeasurement',
  full_name='measurement.unavail.UnavailableMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='measurement.unavail.UnavailableMeasurement.metadata', index=0,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=128,
)

_UNAVAILABLEMEASUREMENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
DESCRIPTOR.message_types_by_name['UnavailableMeasurement'] = _UNAVAILABLEMEASUREMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnavailableMeasurement = _reflection.GeneratedProtocolMessageType('UnavailableMeasurement', (_message.Message,), dict(
  DESCRIPTOR = _UNAVAILABLEMEASUREMENT,
  __module__ = 'measurement_unavail_pb2'
  # @@protoc_insertion_point(class_scope:measurement.unavail.UnavailableMeasurement)
  ))
_sym_db.RegisterMessage(UnavailableMeasurement)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n9com.invap.mulitas.serialization.impl.protobuf.measurement'))
# @@protoc_insertion_point(module_scope)
