# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement-logical.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurement-logical.proto',
  package='measurement.logical',
  syntax='proto2',
  serialized_pb=_b('\n\x19measurement-logical.proto\x12\x13measurement.logical\x1a\x0emetadata.proto\"X\n\x12\x42ooleanMeasurement\x12\r\n\x05value\x18\x01 \x01(\x08\x12\r\n\x05valid\x18\x02 \x01(\x08\x12$\n\x08metadata\x18\x0f \x01(\x0b\x32\x12.metadata.MetadataB;\n9com.invap.mulitas.serialization.impl.protobuf.measurement')
  ,
  dependencies=[metadata__pb2.DESCRIPTOR,])




_BOOLEANMEASUREMENT = _descriptor.Descriptor(
  name='BooleanMeasurement',
  full_name='measurement.logical.BooleanMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='measurement.logical.BooleanMeasurement.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='measurement.logical.BooleanMeasurement.valid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='measurement.logical.BooleanMeasurement.metadata', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=154,
)

_BOOLEANMEASUREMENT.fields_by_name['metadata'].message_type = metadata__pb2._METADATA
DESCRIPTOR.message_types_by_name['BooleanMeasurement'] = _BOOLEANMEASUREMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BooleanMeasurement = _reflection.GeneratedProtocolMessageType('BooleanMeasurement', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANMEASUREMENT,
  __module__ = 'measurement_logical_pb2'
  # @@protoc_insertion_point(class_scope:measurement.logical.BooleanMeasurement)
  ))
_sym_db.RegisterMessage(BooleanMeasurement)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n9com.invap.mulitas.serialization.impl.protobuf.measurement'))
# @@protoc_insertion_point(module_scope)
