# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata-extra.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datatypes_pb2 as datatypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadata-extra.proto',
  package='metadata.extra',
  syntax='proto2',
  serialized_pb=_b('\n\x14metadata-extra.proto\x12\x0emetadata.extra\x1a\x0f\x64\x61tatypes.proto\"D\n\x12\x45xtraMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.datatypes.AnyTypeB8\n6com.invap.mulitas.serialization.impl.protobuf.metadata')
  ,
  dependencies=[datatypes__pb2.DESCRIPTOR,])




_EXTRAMETADATAENTRY = _descriptor.Descriptor(
  name='ExtraMetadataEntry',
  full_name='metadata.extra.ExtraMetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='metadata.extra.ExtraMetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='metadata.extra.ExtraMetadataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=125,
)

_EXTRAMETADATAENTRY.fields_by_name['value'].message_type = datatypes__pb2._ANYTYPE
DESCRIPTOR.message_types_by_name['ExtraMetadataEntry'] = _EXTRAMETADATAENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtraMetadataEntry = _reflection.GeneratedProtocolMessageType('ExtraMetadataEntry', (_message.Message,), dict(
  DESCRIPTOR = _EXTRAMETADATAENTRY,
  __module__ = 'metadata_extra_pb2'
  # @@protoc_insertion_point(class_scope:metadata.extra.ExtraMetadataEntry)
  ))
_sym_db.RegisterMessage(ExtraMetadataEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n6com.invap.mulitas.serialization.impl.protobuf.metadata'))
# @@protoc_insertion_point(module_scope)
