# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata-instrument.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datatypes_pb2 as datatypes__pb2
from . import metadata_extra_pb2 as metadata__extra__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadata-instrument.proto',
  package='metadata.instrument',
  syntax='proto2',
  serialized_pb=_b('\n\x19metadata-instrument.proto\x12\x13metadata.instrument\x1a\x0f\x64\x61tatypes.proto\x1a\x14metadata-extra.proto\"\xbc\x01\n\x12InstrumentMetadata\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x1e\n\x16instrument_description\x18\x02 \x01(\t\x12\x33\n\x15instrument_expiration\x18\x03 \x01(\x0b\x32\x14.datatypes.TimeStamp\x12:\n\x0e\x65xtra_metadata\x18\x04 \x03(\x0b\x32\".metadata.extra.ExtraMetadataEntryB8\n6com.invap.mulitas.serialization.impl.protobuf.metadata')
  ,
  dependencies=[datatypes__pb2.DESCRIPTOR,metadata__extra__pb2.DESCRIPTOR,])




_INSTRUMENTMETADATA = _descriptor.Descriptor(
  name='InstrumentMetadata',
  full_name='metadata.instrument.InstrumentMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_id', full_name='metadata.instrument.InstrumentMetadata.instrument_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument_description', full_name='metadata.instrument.InstrumentMetadata.instrument_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument_expiration', full_name='metadata.instrument.InstrumentMetadata.instrument_expiration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_metadata', full_name='metadata.instrument.InstrumentMetadata.extra_metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=278,
)

_INSTRUMENTMETADATA.fields_by_name['instrument_expiration'].message_type = datatypes__pb2._TIMESTAMP
_INSTRUMENTMETADATA.fields_by_name['extra_metadata'].message_type = metadata__extra__pb2._EXTRAMETADATAENTRY
DESCRIPTOR.message_types_by_name['InstrumentMetadata'] = _INSTRUMENTMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentMetadata = _reflection.GeneratedProtocolMessageType('InstrumentMetadata', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUMENTMETADATA,
  __module__ = 'metadata_instrument_pb2'
  # @@protoc_insertion_point(class_scope:metadata.instrument.InstrumentMetadata)
  ))
_sym_db.RegisterMessage(InstrumentMetadata)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n6com.invap.mulitas.serialization.impl.protobuf.metadata'))
# @@protoc_insertion_point(module_scope)
